# Generated by Django 5.1 on 2025-02-15 05:49

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='registration',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
